### ISSUE TITLE
Does this script works on Ubuntu 22.04 LTS?

### ISSUE THREAD

**Issue by wthe2004** [VidFurlan/Dotfiles#1]
In the README you say that you use arch, but in the script I found something like "apt" so I  guess it works for Ubuntu too?

**Comment by VidFurlan** [comment]
The first part of the script allows the user which programs should be "riced". That part should work almost everywhere. The second part of the script allows you to automatically install the needed packages. Since I use arch I made sure that package installation works with pacman. I also tried implementing debian based distro support but I'm not sure if the package installation works properly.

If it doesn't work you can try installing them manually using apt install. To do so run:
```sudo apt install i3 polybar picom rofi dunst kitty neofetch```
If it still doesn't work, it means that one of the packages isn't in the repositories your distro uses.
